### ISSUE TITLE
feat: blog post about crypto currencies

### ISSUE THREAD

**Issue by SamuelScheit** [s-thom/website-2023#16]
Hi Stuart,

I've seen your blog post about disabling javascript for nextjs and saw this banner

<img width="1789" alt="image" src="https://github.com/user-attachments/assets/c29f0854-0320-4835-93e7-10a60797573a">

I've read your banner as the characters of the page got removed (nice effect btw. xD)
And now I wanted to read more about why you dislike crypto currencies.
You said it could be it's only blog post, but I didn't found any pasts posts about it.
So this is a friendly feature request to ask your opinion about crypto currencies :)

I certainly agree that web3 is a hype VC funded senseless technology, 
but I think the technology for an anonymous decentralized currency has certain advantages.
Especially if you live in a country with a surveilling government.

I would like to read your opinion on the topic and I would be happy to read a blog post about it

Best regards
Samuel

**Comment by s-thom** [comment]
Hi Samuel! Thanks for the question, and for finding the humour in me destroying my own website for some of my visitors. It's good to know it detects your wallet correctly, since I couldn't actually test that part 😄 

You're correct, there is no page explaining my position on cryptocurrencies. The "This could be a whole page in itself" was saying there is more I could write, but recognising that the more I write in the banner the less effective the script is. I don't have the motivation to write a full blog post about my feelings on crypto, so I'll give you the brief version:

The problems that cryptocurrencies are trying to solve are societal, not technological. Heavy-handed government surveillance, the "unbanked" (a euphemism for those living in poverty), and hyperinflation in certain countries are problems that are best solved through social action: bringing down corruption, redistributing wealth, and ready access to food, shelter, and education. No amount of code is going to fix that, it's a human problem involving humans in the human world.

If you find yourself in a situation like the example you gave, where government surveillance is truly worrying you, then I am glad that a solution exists for you and I don't want that safety taken away. However I don't see it as the end goal, it's more of a band-aid that's covering up the underlying problems. Let's fix those.

I hope that satisfies your curiosity. I'm going to close this issue for now, but I'll add an entry to my long list of drafts that there's an opportunity to write about this more.
